// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkforgedyzryllnoswnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrZm9yZ2VkeXpyeWxsbm9zd250Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDAxNjcsImV4cCI6MjA3MzY3NjE2N30.Cl1ldP4uWBXy8SJN3TvC6KA9xVLRbU2ezePI7IJcDp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});